outdated-version: "<red>There is an update available for Simple Chat Moderation: Current: {currentVersion}, latest is {latestVersion}"
chat-mute-message: "<red>[Chat] Chat has been muted by {player}"
chat-unmute-message: "<red>[Chat] Chat has been unmuted by {player}"
chat-muted-message: "<red>The chat is currently muted!"
no-logs-found: "<red>No chat logs found for {player}"
chat-log-header: "<aqua>Chat logs for <blue>{player}</blue> (page {pageNum}/{maxPages}):"
chat-log-entry: "<aqua>{time}: {message}"
chat-log-footer: ""
chat-message-filtered-staff-notification: "<red>[Filter] -> <dark_blue>{sender}: <aqua>{message}"
chat-report-success: "<green>Successfully submitted your report!"
chat-report-notification: "<blue>[Report] <aqua>{reporter} has reported {reported} for <blue>{reason}"
max-same-person-report-time-minutes: 10
already-reported-within-timeframe: "<red>You already reported this player within the last {time} minutes!"
gui-next-page-text: "<blue>Next Page ({current}/{max})"
gui-previous-page-text: "<blue>Previous Page ({current}/{max})"
gui-report-icon-title: "<blue>Report #{reportCount} {reported}"
gui-report-icon-lore:
  - "<aqua>Reporter: {reporter}"
  - "<aqua>Reason: {reason}"
  - "<aqua>At: {time}"
  - "<aqua>Click to handle/generate logs"
  - ""

plugin-info:
  - "<red>Version: {currentVersion}"
  - "<red>Latest Version: {latestVersion}"
  - "<red>Database Type: {database}"
  - "<red>Valid Webhook URL: {webhookEnabled}"

filtered-word-highlight-color: "<yellow>"

word-not-in-filter: "<red>The word <gray>{word} <red> is not in the current filter!"
word-already-in-filter: "<red>The word <gray>{word} <red> is already in the current filter!"
no-filtered-words: "<red>The filter is empty!"
filtered-word-list:
    header: "<gray>-- <green>Filtered Words Page {page}/{maxPages} <gray>--"
    entry: "- <yellow>{word}"
    footer: "<gray>Click: {previousButton} - {nextButton}"
    previous-button: "<green>[Previous]"
    next-button: "<green>[Next]"
    remove-button: "<red>[REMOVE]"
    page-size: 10
    next-page-hover-text: "<gray>Click to go to next page ({nextPage})"
    previous-page-hover-text: "<gray>Click to go to the previous page ({previousPage})"
    remove-word-hover-text: "<gray>Click to remove '{word}'"

cannot-self-report: "<red>You cannot report yourself!"
player-does-not-exist: "<red>The player {player} does not exist!"
invalid-chatlog-page: "<red>This player does not have logs on that page"

report-detail-gui-generate-logs-item: DIAMOND_SWORD
report-detail-gui-generate-logs-item-name: "<aqua>Generate Chat Logs"

report-detail-gui-close-report-item: RED_WOOL
report-detail-gui-close-report-item-name: "<red>Close Report"

report-detail-gui-close-all-reports-item: BEDROCK
report-detail-gui-close-all-reports-item-name: "<dark_red>Close All Reports"

report-detail-gui-back-item: BARRIER
report-detail-gui-back-item-name: "<red>Back"

chat-slow-announcement: "<red>The chat has been slowed to one message per {time} second(s)!"
chat-slow-message: "<red>Hold on, chat is currently slowed! 1 message per {time} second(s)!"
chat-slow-reset: "<red>The chat slow has been lifted!"

chat-cleared: "<red>Chat has been cleared by {player}!"

config-reloaded: "<green>The config has been reloaded!"

no-messages-in-past-time: "<red>This player has not sent any messages in the past {minutes} minutes!"
# When dealing with a chat report, the logs of the reported person
# Starting from the current time PLUS and MINUS  the value of this will be shown.
# So if this value is 15
# And a player gets reported at 6PM
# The chat report will retrieve their logs from 5:45PM until 6:15PM
chat-report-generation-timespan-minutes: 15

report-overview-gui-border-item: GRAY_STAINED_GLASS_PANE

# If set to true, no message will go through.
# If set to false, replace the filtered words with *'s
block-message-on-filter: true

# Notify a user that their message has been filtered
notify-on-filter: true

# Only sent if "notify-on-filter" is set to true
chat-filter-filtered: "<red>[Filter] Your message has been filtered!"


# Whether the chat will remain its state after the restart of a  server
persist-mute-through-restarts: true

# Whether the chat is currently muted
# Value will be ignored when persist-mute-through-restarts is false
chat-muted: false
chat-slow-seconds: 0

webhook-url: ""
embed-title-chat-report: "Chat Report"
embed-body-chat-report: "{sender} reported {reported} for {reason}"
embed-color-chat-report: "#ffaa00"
embed-footer-chat-report: "YourServer.com"

embed-title-chat-filter: "Filtered Message"
embed-body-chat-filter: "{sender}: {message}"
embed-color-chat-filter: "#ffaa00"
embed-footer-chat-filter: "YourServer.com"